### ISSUE TITLE
SkyBlock hibák / elírások

### ISSUE THREAD

**Issue by UDPSendToFailed** [Kuglof/MercilessDestiny#1]
- Enchant NPC nem működik, unknown command
- Spawnon vannak szörnyek
- Harctér warp nem működik, érvénytelen világ
- Boltban a gyapjú részlegen kívül minden inventory neve angol
- Sziget biome menü a /is help parancsot hozza be
- Gyémántblokkot nem lehet lerakni, barrel lesz belőle (update: már a vasat is barrel-be rakja)
- Spawnereket nem számolja bele a sziget értékébe
- Boltban a gyapjút se eladni, se megvenni nem lehet
- A pvp bekapcsolása után nem a spawnra teleportálja a playereket, hanem egy bedrockra a semmi közepén

![kép](https://user-images.githubusercontent.com/16057404/78069660-be1dc000-739a-11ea-9208-e564071b4959.png)

![kép](https://user-images.githubusercontent.com/16057404/78054418-55c2e480-7382-11ea-81bf-ba25c7d97e1c.png)

![kép](https://user-images.githubusercontent.com/16057404/78054115-dc2af680-7381-11ea-8b12-0e655030af30.png)
![kép](https://user-images.githubusercontent.com/16057404/78051708-5f4a4d80-737e-11ea-9670-313cf7eb2801.png)
![kép](https://user-images.githubusercontent.com/16057404/78052289-2fe81080-737f-11ea-8c35-3cd357c53eb5.png)
![kép](https://user-images.githubusercontent.com/16057404/78052312-35455b00-737f-11ea-9796-a2bbd020733b.png)
![kép](https://user-images.githubusercontent.com/16057404/78053096-65d9c480-7380-11ea-820b-9edd0015ac09.png)
![kép](https://user-images.githubusercontent.com/16057404/78053260-a33e5200-7380-11ea-9683-35c8dea258a0.png)
![kép](https://user-images.githubusercontent.com/16057404/78053464-edbfce80-7380-11ea-9493-53d5ede0a889.png)
![kép](https://user-images.githubusercontent.com/16057404/78053471-f1535580-7380-11ea-8d54-7b8df344d05b.png)
![kép](https://user-images.githubusercontent.com/16057404/78054819-e8fc1a00-7382-11ea-9f17-6c837f9d8fb6.png)

- Pár biome / érhetsz el
![kép](https://user-images.githubusercontent.com/16057404/78053119-6d996900-7380-11ea-9024-2f1b07c0bdf8.png)

- Minél
![kép](https://user-images.githubusercontent.com/16057404/78052943-1d220b80-7380-11ea-9992-39d3e5725c65.png)

**Comment by Kuglof** [comment]
Javítva minden! Köszönöm!
